db.genre.insert({"genre_name" : "Alternative", "genre_notes" : null });
db.genre.insert({"genre_name" : "Blues", "genre_notes" : null });
db.genre.insert({"genre_name" : "Classical", "genre_notes" : null });
db.genre.insert({"genre_name" : "Country", "genre_notes" : null });
db.genre.insert({"genre_name" : "Dance", "genre_notes" : null });
db.genre.insert({"genre_name" : "Electronic", "genre_notes" : null });
db.genre.insert({"genre_name" : "Folk", "genre_notes" : null });
db.genre.insert({"genre_name" : "Hip Hop", "genre_notes" : null });
db.genre.insert({"genre_name" : "Indie", "genre_notes" : null });
db.genre.insert({"genre_name" : "Jazz", "genre_notes" : null });
db.genre.insert({"genre_name" : "Latin", "genre_notes" : null });
db.genre.insert({"genre_name" : "Pop", "genre_notes" : null });
db.genre.insert({"genre_name" : "Punk Rock", "genre_notes" : null });
db.genre.insert({"genre_name" : "R&B", "genre_notes" : null });
db.genre.insert({"genre_name" : "Reggae", "genre_notes" : null });
db.genre.insert({"genre_name" : "Rock", "genre_notes" : null });
db.genre.insert({"genre_name" : "Ska", "genre_notes" : null });
db.genre.insert({"genre_name": "Soul", "genre_notes": null });
db.genre.insert({"genre_name": "Soundtrack", "genre_notes": null });
db.genre.insert({"genre_name" : "World", "genre_notes" : null });
