db.company.insert({ "co_name" : "Drag City", "co_description" : "" });
db.company.insert({ "co_name" : "Island Records", "co_description" : "" });
db.company.insert({ "co_name" : "Epitaph Records", "co_description" : "" });
db.company.insert({ "co_name" : "Ruthless Records", "co_description" : "" });
db.company.insert({ "co_name" : "Aftermath Entertainment", "co_description" : "" });
db.company.insert({ "co_name" : "Roc-A-Fella Records", "co_description" : "" });
db.company.insert({ "co_name" : "Dream On Records", "co_description" : "" });
db.company.insert({ "co_name" : "Republic Records", "co_description" : "" });
db.company.insert({ "co_name" : "Epic Records", "co_description" : "" });
db.company.insert({ "co_name" : "Sub Pop", "co_description" : "" });
db.company.insert({ "co_name" : "DGC Records", "co_description" : "" });
db.company.insert({ "co_name" : "Fat Wreck Chords", "co_description" : "" });
db.company.insert({ "co_name" : "Columbia", "co_description" : "" });
db.company.insert({ "co_name" : "Merge Records", "co_description" : "" });
db.company.insert({ "co_name" : "RCA Records", "co_description" : "" });
db.company.insert({ "co_name" : "Splash Records", "co_description" : "" });
db.company.insert({ "co_name" : "Medicine Label", "co_description" : "" });
db.company.insert({ "co_name" : "Hollywood Records", "co_description" : "" });
db.company.insert({ "co_name" : "Rhino Records", "co_description" : "" });
db.company.insert({ "co_name" : "Arista Records", "co_description" : "" });
db.company.insert({ "co_name" : "Virgin Records", "co_description" : "" });
db.company.insert({ "co_name" : "A&M Records", "co_description" : "" });
db.company.insert({ "co_name" : "Apple Records", "co_description" : "" });
db.company.insert({ "co_name" : "Vertigo Records", "co_description" : "" });
db.company.insert({ "co_name" : "Flyte Tyme Studios", "co_description" : "" });
db.company.insert({ "co_name" : "The Boardwalk Entertainment Co", "co_description" : "" });
db.company.insert({ "co_name" : "Berhane Sound System", "co_description" : "" });
db.company.insert({ "co_name" : "Asian Man Records", "co_description" : "" });
db.company.insert({ "co_name" : "Revelation Records", "co_description" : "" });
db.company.insert({ "co_name" : "Far Out Records", "co_description" : "" });
db.company.insert({ "co_name" : "Lookout! Records", "co_description" : "" });
db.company.insert({ "co_name" : "Prestige Records", "co_description" : "" });
db.company.insert({ "co_name" : "Track Records", "co_description" : "" });
db.company.insert({ "co_name" : "Riverside Records", "co_description" : "" });
